/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-07-22 04:50:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.awesome.member.model.vo.Member;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1562298110696L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/Dropbox/workspace/Awesome/Awesome/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/Dropbox/workspace/Awesome/Awesome/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/Dropbox/workspace/Awesome/Awesome/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.awesome.member.model.vo.Member");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Awesome</title>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.4.0.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bxslider-4-4.2.12/src/js/jquery.bxslider.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/sockjs/1/sockjs.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://code.getmdl.io/1.3.0/material.indigo-pink.min.css\">\r\n");
      out.write("    <script defer src=\"https://code.getmdl.io/1.3.0/material.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/fullpage.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bxslider-4-4.2.12/src/js/jquery.bxslider.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("     \r\n");
      out.write("    <!-- 20190706 23:48  -->\r\n");
      out.write("    <!-- google login 김용빈 -->\r\n");
      out.write("\t<meta name=\"google-signin-scope\" content=\"profile email\">\r\n");
      out.write("    <meta name=\"google-signin-client_id\" content=\"620340826519-n25olunhj7rerh7f6fde1umslcfvgquf.apps.googleusercontent.com\">\r\n");
      out.write("    <script src=\"https://apis.google.com/js/platform.js\" async defer></script>\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("     <!-- WebSocket:sock.js CDN -->\r\n");
      out.write("    <!-- <script src=\"https://cdnjs.cloudflare.com/ajax/libs/sockjs-client/1.3.0/sockjs.js\"></script>\r\n");
      out.write("    WebSocket: stomp.js CDN\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/stomp.js/2.3.3/stomp.js\"></script> -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- 20190721 김용빈 -->\r\n");
      out.write("    <!-- Tiny Nice Confirmation Popup Plugin With jQuery - H-confirm-alert -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/H-confirm-alert.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/H-confirm-alert.css\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" \r\n");
      out.write("        integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js\" integrity=\"sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- 구글 폰트 -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Jua|Luckiest+Guy&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    \r\n");
      out.write("    *{\r\n");
      out.write("\t\tfont-family: 'Jua', sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("        .mdl-layout__header-row{background: white;}\r\n");
      out.write("        .mdl-layout__content{overflow-y:hidden;}\r\n");
      out.write("        .mdl-layout__header-row .mdl-navigation__link{color:black;}\r\n");
      out.write("        .mdl-layout-title{color:black;}\r\n");
      out.write("        #awe-logo-img{height:30px;}\r\n");
      out.write("        #modalBody{ flex-direction : row; justify-content : space-between; align-items : center;align-content : center;max-width : 100%;     }\r\n");
      out.write("        #modalBody #modalList{flex : 1 1 0; margin : auto; display : flex; flex-direction : column;justify-content : space-between; }\r\n");
      out.write("        #modalBody #modalList .btn{flex : 1 1 0; margin : auto;margin-top : 1%; width:100%;}\r\n");
      out.write("        #modalBody .modal-body{flex : 1 1 0; margin : auto; }\r\n");
      out.write("        #login{font-size: 16px;  right: 50px; width:90px;  }\r\n");
      out.write("        .mdl-badge{ border: 1px solid white; background: white;}\r\n");
      out.write("      \t\t.flex{\r\n");
      out.write("\t\t\tdisplay : flex; \r\n");
      out.write("          \t\tflex-direction : row;\r\n");
      out.write("          \t\tjustify-content : flex-end;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#titleLogo:hover{\r\n");
      out.write("\t\t\tcursor:pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("       <!-- Modal -->\r\n");
      out.write("        <div class=\"modal fade\" id=\"loginmodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("          <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("              <h5 class=\"modal-title\" id=\"exampleModalLabel\">로그인</h5>\r\n");
      out.write("              <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("              </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/memberLogin.do\" method=\"post\" onsubmit=\"return validate();\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <span>아이디</span>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"memberId\" id=\"memberId\" placeholder=\"이메일 형태의 아이디 입력\" required>  <br>\r\n");
      out.write("                <span>비밀번호</span>\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" name=\"password\" id=\"password\" required>  <br>\r\n");
      out.write("                <div class=\"flex\">\r\n");
      out.write("\t            \t<div class=\"custom-control custom-checkbox\">\r\n");
      out.write("\t\t\t\t\t  <input type=\"checkbox\" class=\"custom-control-input\" name=\"saveMemberId\" id=\"saveMemberId\">\r\n");
      out.write("\t\t\t\t\t  <label class=\"custom-control-label\" for=\"saveMemberId\">Save Id</label>\r\n");
      out.write("\t\t\t\t\t</div> &nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<div class=\"custom-control custom-checkbox\">\r\n");
      out.write("\t\t\t\t\t  <input type=\"checkbox\" class=\"custom-control-input\" name=\"autoLogin\" id=\"autoLogin\">\r\n");
      out.write("\t\t\t\t\t  <label class=\"custom-control-label\" for=\"autoLogin\">Auto Login</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            \t<br />\r\n");
      out.write("                <!-- <a href=\"http://localhost/awesome/member/findMember.do\">아이디/비밀번호를 잃어버렸습니까?.</a> <br> <br> -->\r\n");
      out.write("                <a href=\"#\" id=\"findMember\" onclick=\"findMember()\">아이디/비밀번호를 잃어버렸습니까?.</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\">로그인</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("                <!-- 20190706 23:48  -->\r\n");
      out.write("                <!-- google login 김용빈 -->\r\n");
      out.write("               \t    <div id=\"btnJoinGoogle\" style=\"text-align:center\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${google_url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<img width=\"223\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/btn_google.png\"/></a></div>\r\n");
      out.write("\t\t\t\t\t<br>  \r\n");
      out.write("                <!-- 20190709 09:36  -->\r\n");
      out.write("                <!-- naver login 김용빈 -->             \r\n");
      out.write("\t                <div id=\"naver_id_login\" style=\"text-align:center\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${naver_url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<img width=\"223\" src=\"https://developers.naver.com/doc/review_201802/CK_bEFnWMeEBjXpQ5o8N_20180202_7aot50.png\"/></a></div>\r\n");
      out.write("\t\t\t\t\t<br>  \r\n");
      out.write("                       \r\n");
      out.write("     </div>\r\n");
      out.write("   </div>\r\n");
      out.write(" </div>\r\n");
      out.write("       \r\n");
      out.write("   <!-- 20190705 12:54 김용빈  -->\r\n");
      out.write("<!-- 회원가입 모달 추가 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"memberEnrollModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 회원가입 모달 끝 -->\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("    <section id=\"content\">\r\n");
      out.write("    <!-- Always shows a header, even in smaller screens. -->\r\n");
      out.write("    <div class=\"mdl-layout mdl-js-layout mdl-layout--fixed-header\">\r\n");
      out.write("      <header class=\"mdl-layout__hea.der\">\r\n");
      out.write("        <div class=\"mdl-layout__header-row\">\r\n");
      out.write("          <!-- Title -->\r\n");
      out.write("          <span id=\"titleLogo\" class=\"mdl-layout-title\"><img id=\"awe-logo-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/awesome-nontext.png\" alt=\"\" /> &nbsp;&nbsp;Awesome</span>\r\n");
      out.write("          <!-- Add spacer, to align navigation to the right -->\r\n");
      out.write("          <div class=\"mdl-layout-spacer\"></div>\r\n");
      out.write("          <!-- Navigation. We hide it in small screens. -->\r\n");
      out.write("          <nav class=\"mdl-navigation mdl-layout--large-screen-only\">\r\n");
      out.write("            <!-- Icon badge -->\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            <script>\r\n");
      out.write("                $(\"#demo-menu-lower-left\").on(\"click\",function(){\r\n");
      out.write("                    var mCode = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberLoggedIn.memberCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                    console.log(\"hello chatBox\")\r\n");
      out.write("                    $.ajax({ \r\n");
      out.write("                    \turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sock/selectMyChat\", \r\n");
      out.write("                        data: mCode,\r\n");
      out.write("                    success : function(data){\r\n");
      out.write("                        $(\"ul#chatBox\").html(data.html)\r\n");
      out.write("                    },\r\n");
      out.write("                    error: function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("                        console.log(\"ajax처리실패! : \"+jqxhr.status);\r\n");
      out.write("                    }\r\n");
      out.write("                })\r\n");
      out.write("                    \r\n");
      out.write("                })\r\n");
      out.write("                \r\n");
      out.write("                $(\"li.mdl-menu__item\").on(\"click\",function(){\r\n");
      out.write("                    var mCode = $(this).attr(\"id\");\r\n");
      out.write("                    \r\n");
      out.write("                    $.ajax({\r\n");
      out.write("                        url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sock/selectMyChat\",\r\n");
      out.write("                        data: mCode,\r\n");
      out.write("                        success: function(data){\r\n");
      out.write("                            \r\n");
      out.write("                        },error: function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("                            console.log(\"ajax처리 실패! : \"+kqxhr.status)\r\n");
      out.write("                        }\r\n");
      out.write("                        \r\n");
      out.write("                    })\r\n");
      out.write("                })\r\n");
      out.write("                \r\n");
      out.write("            </script>\r\n");
      out.write("            \r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <script>\r\n");
      out.write("            \tfunction signUp(){\r\n");
      out.write("    \t\t\t\t$(\"#signUp\").trigger(\"click\");\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("            </script>\r\n");
      out.write("            \r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("          </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("      </header>\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("      <main class=\"mdl-layout__content\">\r\n");
      out.write("        <div class=\"page-content\">\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#titleLogo\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index\";\r\n");
      out.write("   });\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("function myInfo(){\r\n");
      out.write("\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/memberInfo.do\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function findMember(){\r\n");
      out.write("\twindow.open(\"/awesome/member/findMember.do\",\"pop\",\"width=570,height=420, scrollbars=yes, resizable=yes\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("<!-- 20190705 12:54 김용빈  -->\r\n");
      out.write("<!-- 회원가입 모달 추가 - -->\r\n");
      out.write("    $(function(){\r\n");
      out.write("        $(\"#signUp\").on(\"click\",function(){\r\n");
      out.write("        \t\r\n");
      out.write("            $.ajax({ \r\n");
      out.write("                 url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/memberEnroll.do\", \r\n");
      out.write("                 data:\"memberId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("                success : function(data){\r\n");
      out.write("                    $(\"#memberEnrollModal .modal-content\").empty();\r\n");
      out.write("                    $(\"#memberEnrollModal .modal-content\").append(data);\r\n");
      out.write("                    \r\n");
      out.write("                },\r\n");
      out.write("                error: function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("                    console.log(\"ajax처리실패! : \"+jqxhr.status);\r\n");
      out.write("                    console.log(jqxhr);\r\n");
      out.write("                    console.log(textStatus);\r\n");
      out.write("                    console.log(errorThrown);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("<!--20190711 09:34 김용빈-->\r\n");
      out.write("    $(\"#logOut\").on(\"click\",function(){\r\n");
      out.write("        \r\n");
      out.write("        var logout=confirm(\"정말로 로그아웃?\");\r\n");
      out.write("        \r\n");
      out.write("        if(logout){\r\n");
      out.write("            location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/memberLogout.do';\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("<!-- 20190715 12:35 김용빈  -->\r\n");
      out.write("<!-- 아이디 저장 -->\r\n");
      out.write("    $(function(){\r\n");
      out.write("        $(\"#memberId\").val(localStorage.getItem(\"awesomeSaveMemberId\"));\r\n");
      out.write("        \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    function validate(){\r\n");
      out.write("        if($(\"#saveMemberId\").prop(\"checked\")){\r\n");
      out.write("            var value = $(\"#memberId\").val();\r\n");
      out.write("            localStorage.setItem(\"awesomeSaveMemberId\", value);\r\n");
      out.write("        }else{\r\n");
      out.write("            localStorage.setItem(\"awesomeSaveMemberId\", \"\");\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        return true;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\t/* 20190721 김용빈 */\r\n");
      out.write("\t//자동로그인 경고창\r\n");
      out.write("\t$(\"#autoLogin\").on(\"click\",function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#autoLogin\").prop(\"checked\")){\r\n");
      out.write("\t\t\t$.confirm.show({\r\n");
      out.write("\t\t\t\t  \"message\": \"개인정보보호를 위해 주의해주세요 <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;자동로그인 쿠키는 일주일간 보관됩니다. \",\r\n");
      out.write("\t\t\t\t  \"yes\": function (){\r\n");
      out.write("\t\t\t\t  },\r\n");
      out.write("\t\t\t\t  \"no\": function (){\r\n");
      out.write("\t\t\t\t\t  $(\"#autoLogin\").prop(\"checked\",false);\r\n");
      out.write("\t\t\t\t  },\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("  \r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    var sock = new SockJS(\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("    \r\n");
      out.write("    //web socket 메세지보내면 자동 실행\r\n");
      out.write("    sock.onmessage = onMessage;\r\n");
      out.write("    sock.onclose = onClose;\r\n");
      out.write("    /* $(function(){\r\n");
      out.write("        sendMessage();\r\n");
      out.write("    }) */\r\n");
      out.write("    \r\n");
      out.write("    function sendMessage(){\r\n");
      out.write("        sock.send(\"hello ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberLoggedIn.memberCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function onMessage(evt){\r\n");
      out.write("        console.log(\"onMessage 호출됨\")\r\n");
      out.write("        var data = evt.data;\r\n");
      out.write("        var sessionId = null;\r\n");
      out.write("        var message = null;\r\n");
      out.write("        \r\n");
      out.write("        //문자열을 split\r\n");
      out.write("        var strArray = data.split(\"|\");\r\n");
      out.write("        \r\n");
      out.write("        for(var i=0; i<strArray.length; i++){\r\n");
      out.write("            console.log(\"str[\"+i+\"]\" + strArray[i])\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        sessionId = strArray[0];\r\n");
      out.write("        message = strArray[1];\r\n");
      out.write("        \r\n");
      out.write("        console.log(\"멤버 코드 :\" +sessionId)\r\n");
      out.write("        console.log(\"메시지 : \"+message)\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function onClose(evt){\r\n");
      out.write("        console.log(\"연결 끊김\")\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/common/header.jsp(157,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ memberLoggedIn != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <button id=\"demo-menu-lower-left\" data-badge=\"♥\" class=\"mdl-button mdl-js-button mdl-badge\">Mesaage</button>\r\n");
          out.write("                    \r\n");
          out.write("                    <ul class=\"mdl-menu mdl-menu--bottom-left mdl-js-menu mdl-js-ripple-effect\" for=\"demo-menu-lower-left\" id=\"chatBox\">\r\n");
          out.write("                    </ul>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/common/header.jsp(197,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberLoggedIn == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            \t<input type=\"button\" class=\"btn btn-light mdl-navigation__link\" onclick=\"signUp()\" value=\"Sign Up\"></input>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/common/header.jsp(207,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberLoggedIn != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t            <input type=\"button\" class=\"btn btn-light mdl-navigation__link\" id=\"menu2\" value=\"소개팅\" />\r\n");
          out.write("\t            <input type=\"button\" class=\"btn btn-light mdl-navigation__link\" id=\"menu2\" value=\"번개팅\" />\r\n");
          out.write("\t            <input type=\"button\" class=\"btn btn-light mdl-navigation__link\" id=\"menu2\" value=\"동네 친구\" />\r\n");
          out.write("\t            <input type=\"button\" class=\"btn btn-light mdl-navigation__link\" id=\"menu2\" value=\"소모임\" />\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/common/header.jsp(214,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberLoggedIn == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <input type=\"button\" class=\"btn btn-light mdl-navigation__link\" id=\"login\" data-toggle=\"modal\" data-target=\"#loginmodal\" value=\"Login\"></input>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/common/header.jsp(217,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberLoggedIn != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            \t<input type=\"button\" class=\"btn btn-light mdl-navigation__link\" onclick=\"myInfo()\" value=\"My Info\"></input>\r\n");
          out.write("            \t<input type=\"button\" class=\"btn btn-light mdl-navigation__link\" id=\"logOut\" value=\"LogOut\"></input>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/common/header.jsp(323,27) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/echo");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
