/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-07-22 04:22:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.awesome.member.model.vo.Member;

public final class randing_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1562298110696L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/Dropbox/workspace/Awesome/Awesome/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/Dropbox/workspace/Awesome/Awesome/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/Dropbox/workspace/Awesome/Awesome/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.awesome.member.model.vo.Member");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Awesome", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("    \tbody{margin: 0 0; overflow-y: hidden;}\r\n");
      out.write("\t\thtml{overflow: hidden; overflow-y:hidden;}\r\n");
      out.write("\t\theader div.video{position: relative; }\r\n");
      out.write("\t\theader div.video h1{position: absolute; top: 0px; display: none;}\r\n");
      out.write("\t\t#loginAfter{margin: 9px 0; padding: 7px 15px; font-size: 16px; position: fixed; right: 100px; width:90px;  z-index: 999; display: none;display : flex; flex-direction : row;justify-content : space-between; }\r\n");
      out.write("\t\theader #content-container{min-height: 500px;  display: none; }\r\n");
      out.write("\t\theader #content-container #index-image{position: relative; text-align: center; background-color: #fff; }\r\n");
      out.write("\t\theader #content-container #index-image img{opacity: 0.8; width:1024px; height: 660px;}\r\n");
      out.write("\t\theader #content-container #index-image #pTag{position: absolute;top: 0px; left:0px; text-align: center; padding-top: 200px; z-index: 1; }\r\n");
      out.write("\t\theader #content-container #index-image #pTag p{ color:white; text-align: center; font-size:80px; margin: 0 0; margin-bottom: 50px; text-shadow: 0 1px 6px rgba(0,0,0,.27)}\r\n");
      out.write("\t\theader #content-container #index-image #pTag .mybutton-css{width: 250px;  height: 50px; background: linear-gradient(262deg, #ff7854, #fd267d); \r\n");
      out.write("\t\t        box-shadow: 0 1px 6px 0 rgba(0,0,0,.27); border:0px; font-size:20px; }\r\n");
      out.write("\t\t.target{height: 500px;}\r\n");
      out.write("\t\t#content-container #page-introduce .container .row .col img#flx{ margin-right:79px; height: 358px; width:310px; margin-top: 100px; border-radius: 60px;}\r\n");
      out.write("\t\theader #content-container #page-introduce{background: #fff;}\r\n");
      out.write("\t\t.icon{width: 36px; margin-right: 10px; margin-top:10px;}\r\n");
      out.write("\t\t.icon:last-of-type{margin-right:90px;}\r\n");
      out.write("\t\t.fp-tableCell{width:100%;}\r\n");
      out.write("\t\t#page-introduce{width:100%; height:100%; display:block;}\r\n");
      out.write("\t\t#page-introduce div.inline-div{display:inline-block;}\r\n");
      out.write("\t\t#page-introduce div#select-info{width:25%; height:100%; background:#4e6168;}\r\n");
      out.write("\t\t#page-introduce div#select-page-introduce{width:74%; height:100%; }\r\n");
      out.write("\t\tdiv.bx-viewport{width:100%; height:100%;}\r\n");
      out.write("\t\t.img-select{width:150px; height:100px; border:1px solid;}\r\n");
      out.write("\t\t#select-info{text-align:center;}\r\n");
      out.write("\t\t#select-info img{width:200px; height:150px;}\r\n");
      out.write("\t\t#select-page-introduce{position:absolute; padding:150px 150px;}\r\n");
      out.write("\t\t#select-page-introduce div img{width:672px; height:400px;}\r\n");
      out.write("\t\t.flex{\r\n");
      out.write("\t\t\t\t\tdisplay : flex; \r\n");
      out.write("            \t\tflex-direction : row;\r\n");
      out.write("            \t\tjustify-content : flex-end;\r\n");
      out.write("\t\t\t\t}\t\t\r\n");
      out.write("    </style>\r\n");
      out.write("    <header>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"video\">\r\n");
      out.write("            <video autoplay loop muted >\r\n");
      out.write("                <source src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/video/Circle - 17445.mp4\" type=\"video/mp4\" />\r\n");
      out.write("            </video>\r\n");
      out.write("            \r\n");
      out.write("            <h1 id=\"logo\">Awesome</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"content-container\">\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"index-image\" class=\"section\" >\r\n");
      out.write("            \r\n");
      out.write("                <div class=\"bxslider\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/blue-2564660_1280.jpg\" alt=\"\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/portrait-3204843_640.jpg\" alt=\"\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/workplace-1245776_1280.jpg\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pTag\">\r\n");
      out.write("                    <p> &nbsp;&nbsp;&nbsp;Awesome</p>\r\n");
      out.write("                    \r\n");
      out.write("                   <!-- 20190705 12:53 김용빈  -->\r\n");
      out.write("                   <!-- 회원가입 모달 추가 -->\r\n");
      out.write("                       <!-- 20190708 로그인 분기처리 :김용빈-->\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("            <div id=\"page-introduce\" class=\"section\" >\r\n");
      out.write("            \t<div id=\"select-info\" class=\"inline-div\">\r\n");
      out.write("            \t<br />\r\n");
      out.write("            \t\t<img id=\"sel-1st\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/sampleimage.png\" alt=\"\" /> <br /><br />\r\n");
      out.write("            \t\t<img id=\"sel-2nd\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/sampleimage.png\" alt=\"\" /> <br /><br />\r\n");
      out.write("            \t\t<img id=\"sel-3rd\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/sampleimage.png\" alt=\"\" /> <br /><br />\r\n");
      out.write("            \t\t<img id=\"sel-4th\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/sampleimage.png\" alt=\"\" /> <br /><br />\r\n");
      out.write("            \t\t<img id=\"sel-5th\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/sampleimage.png\" alt=\"\" /> <br /><br />\r\n");
      out.write("            \t</div>\r\n");
      out.write("            \t<div id=\"select-page-introduce\" class=\"inline-div\">\r\n");
      out.write("            \t\t<div class=\"intro-img\" id=\"intro-1st\">\r\n");
      out.write("            \t\t\t<h2>소개팅</h2><br />\r\n");
      out.write("            \t\t\t<h4>설렘을 찾아보세요!</h4> <br />\r\n");
      out.write("            \t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/sampleimage.png\" alt=\"\" />\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"intro-img\" id=\"intro-2nd\">\r\n");
      out.write("            \t\t\t<h2>동네친구</h2> <br />\r\n");
      out.write("            \t\t\t<h4>내 근처 친구를 만나보세요!</h4> <br />\r\n");
      out.write("            \t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/sampleimage.png\" alt=\"\" />\r\n");
      out.write("            \t\t\t\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"intro-img\" id=\"intro-3rd\">\r\n");
      out.write("\t\t\t\t\t\t<h2>번개팅</h2> <br />\r\n");
      out.write("\t\t\t\t\t\t<h4>약속과 약속사이 비는 시간에 새로운 만남!</h4> <br />    \t\t\t\r\n");
      out.write("            \t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/sampleimage.png\" alt=\"\" />\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"intro-img\" id=\"intro-4th\">\r\n");
      out.write("            \t\t\t<h2>모임</h2> <br />\r\n");
      out.write("            \t\t\t<h4>나의 취미를 공유 하는 모임</h4> <br />\r\n");
      out.write("            \t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/sampleimage.png\" alt=\"\" />\r\n");
      out.write("            \t\t\t\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"intro-img\" id=\"intro-5th\">\r\n");
      out.write("            \t\t\t<h2>동창</h2> <br />\r\n");
      out.write("            \t\t\t<h4>학교 친구들을 찾을 수있게 도와드립니다.</h4> <br />\r\n");
      out.write("            \t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/sampleimage.png\" alt=\"\" />\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \t\t//first 페이지 이미지슬라이드\r\n");
      out.write("            $(function(){\r\n");
      out.write("                $('.bxslider').bxSlider({\r\n");
      out.write("                    auto: true,\r\n");
      out.write("                    autoControls: true,\r\n");
      out.write("                    stopAutoOnClick: true,\r\n");
      out.write("                    pager: true\r\n");
      out.write("            });\r\n");
      out.write("            // fullpage .js\r\n");
      out.write("            $(\".bx-controls.bx-has-controls-direction.bx-has-controls-auto.bx-has-pager\").css(\"display\",\"none\")\r\n");
      out.write("                var myFullpage = new fullpage('#content-container', {\r\n");
      out.write("            /*  sectionsColor: ['#1bbc9b', '#4BBFC3', '#7BAABE', 'whitesmoke', '#ccddff'],*/\r\n");
      out.write("                anchors: ['firstPage', 'secondPage', '3rdPage', '4thpage', 'lastPage'],\r\n");
      out.write("                menu: '#menu',\r\n");
      out.write("                lazyLoad: true\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            //웹크기 변경시 홈출되는 함수\r\n");
      out.write("            $(window).resize(function(){\r\n");
      out.write("            \t$(\"#page-introduce div\").width($(window).innerWidth()/2 -10)\r\n");
      out.write("    \t\t\t$(\"#page-introduce .fp-tableCell\").width(\"100%\");\r\n");
      out.write("            \t$(\"#page-introduce\").width(\"100%\");\r\n");
      out.write("            \t$(\"#select-info\").width(\"25%\");\r\n");
      out.write("            \t$(\"#select-page-introduce\").width(\"74%\");\r\n");
      out.write("            \t$(\".bxslider img\").height($(window).innerHeight()-60)\r\n");
      out.write("            })\r\n");
      out.write("                //video 사이즈 조절\r\n");
      out.write("                $(\"video\").width($(window).innerWidth())\r\n");
      out.write("                \r\n");
      out.write("                if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty memberLoggedIn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\r\n");
      out.write("                \t\r\n");
      out.write("\t                $(\"#logo\").css(\"top\",$(\"video\").innerHeight()/2)\r\n");
      out.write("\t                    .css(\"left\",$(\"video\").innerWidth()/2 -95)\r\n");
      out.write("\t                    .fadeIn(3000,function(){\r\n");
      out.write("\t                        $(\"div.video\").remove();\r\n");
      out.write("\t                        $(\"#content-container\").fadeIn(1500);\r\n");
      out.write("\t                        $(\"#login\").css(\"top\",\"0px\").css(\"display\",\"block\");\r\n");
      out.write("\t                        $(\"#loginAfter\").css(\"top\",\"0px\").css(\"display\");\r\n");
      out.write("\t                        $(\"html\").css(\"overflow-y\",\"auto\");\r\n");
      out.write("                    })\r\n");
      out.write("                }else{\r\n");
      out.write("                \t$(\"video\").remove();\r\n");
      out.write("                \t$(\"#content-container\").fadeIn(1500);\r\n");
      out.write("                \t$(\"#login\").css(\"top\",\"0px\").css(\"display\",\"block\");\r\n");
      out.write("                    $(\"#loginAfter\").css(\"top\",\"0px\").css(\"display\");\r\n");
      out.write("                    $(\"html\").css(\"overflow-y\",\"auto\");\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                    \r\n");
      out.write("\t\t\t\t$(\".page-introduce .fp-tableCell\").width(\"100%\");\t\r\n");
      out.write("                $(\".bx-viewport\").height(\"100%\").width(\"100%\");\r\n");
      out.write("                $(\"#index-image img\").width($(window).width())\r\n");
      out.write("                        .height($(window).innerHeight()-60)\r\n");
      out.write("                $(\"#index-image #main-image\").css(\"height\",\"500px\")\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                $(\"#pTag\").width($(\"#index-image\").children(\"img\").width())\r\n");
      out.write("\r\n");
      out.write("                $(\".tp-tableCell\").width(\"100%\")\r\n");
      out.write("\r\n");
      out.write("                $(\"#icon-logo\").css(\"width\",\"120px\").css(\"height\",\"50px\")\r\n");
      out.write("                $(\"#myModal\").prop(\"z-index\",\"100\").children().prop(\"z-index\",\"100\")\r\n");
      out.write("\r\n");
      out.write("                $(\"#index-image\").siblings().width($(window).width()).height($(window).height())\r\n");
      out.write("\t\r\n");
      out.write("                \r\n");
      out.write("                $(\"#select-page-introduce div\").css(\"display\",\"none\").eq(0).css(\"display\",\"inline-block\");\r\n");
      out.write("                \r\n");
      out.write("                $(\"#select-info img\").on(\"click\",function(){\r\n");
      out.write("                \tif($(this).attr(\"id\") == \"sel-1st\") changeImg(\"intro-1st\")\r\n");
      out.write("                \telse if($(this).attr(\"id\") == \"sel-2nd\") changeImg(\"intro-2nd\")\r\n");
      out.write("                \telse if($(this).attr(\"id\") == \"sel-3rd\") changeImg(\"intro-3rd\")\r\n");
      out.write("                \telse if($(this).attr(\"id\") == \"sel-4th\") changeImg(\"intro-4th\")\r\n");
      out.write("                \telse if($(this).attr(\"id\") == \"sel-5th\") changeImg(\"intro-5th\")\r\n");
      out.write("                \t\r\n");
      out.write("                })\r\n");
      out.write("            })\r\n");
      out.write("            function changeImg(idd){\r\n");
      out.write("            \t$(\"#select-page-introduce div\").css(\"display\",\"none\");\r\n");
      out.write("            \t$(\"#\"+idd+\"\").css(\"display\",\"inline-block\");\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("    \t\r\n");
      out.write("        </script>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/common/randing.jsp(70,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.OAuth eq 'NoMember'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            \t\t\t<script>$(function(){\r\n");
          out.write("            \t\t\t\t\t\t\talert(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\");\r\n");
          out.write("            \t\t\t\t\t\t\t$(\"#signUp\").trigger(\"click\");\r\n");
          out.write("            \t\t\t\t\t\t\t});</script>\r\n");
          out.write("            \t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/common/randing.jsp(76,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.memberLoggedIn==null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <button type=\"button\" class=\"btn btn-primary mybutton-css\" id=\"signUp\" \r\n");
          out.write("                    \t\t\tdata-toggle=\"modal\"\r\n");
          out.write("\t    \t\t\t\t\t\tdata-target=\"#memberEnrollModal\">Sign up</button>\r\n");
          out.write("\t    \t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
