/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-07-23 00:19:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1562298110696L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/Dropbox/workspace/Awesome/Awesome/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/Dropbox/workspace/Awesome/Awesome/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/Dropbox/workspace/Awesome/Awesome/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>TEST</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.4.0.js\"></script>\r\n");
      out.write("<!-- 부트스트랩관련 라이브러리 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css\" integrity=\"sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js\" integrity=\"sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=gf3hncw6qx\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=gf3hncw6qx&submodules=geocoder\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("section.main-section{\r\n");
      out.write("\tborder: 6px solid black;\r\n");
      out.write("\tborder-radius: 80px;\r\n");
      out.write("\twidth: 700px;\r\n");
      out.write("\tmin-height: 500px;\r\n");
      out.write("\t\r\n");
      out.write("\tdisplay: inline-flex;\r\n");
      out.write("}\r\n");
      out.write("div.profile-photo{\r\n");
      out.write("\tborder: 1px solid red;\r\n");
      out.write("\twidth: 49%;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\t\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("div.profile-text{\r\n");
      out.write("\tborder: 1px solid blue;\r\n");
      out.write("\twidth: 49%;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("ul.profile-list{\r\n");
      out.write("\tpadding: 60px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("pageTitle", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("awesome 인덱스", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("<script>\n");
      out.write("function city_local_info(){\n");
      out.write("\t/* var param = {};\n");
      out.write("\tparam.key = '82C91404-6AF0-3A92-8D77-CB8CCEE31F42';\n");
      out.write("\tparam.domain = 'http://localhost/awesome/';\n");
      out.write("\t\n");
      out.write("\tvar jsonParam = JSON.stringify(param); */\n");
      out.write("\t\n");
      out.write("\t$.ajax({\n");
      out.write("\t\turl : 'http://api.vworld.kr/req/data?service=data&request=GetFeature&data=LT_C_ADSIGG_INFO&key=C5041472-87EC-3778-B5A6-95598389672F&domain=',\n");
      out.write("\t\tdataType: \"json\",\n");
      out.write("\t\tcontentType: \"application/json; charset=UTF-8\",\n");
      out.write("\t\tsuccess: function(data){\n");
      out.write("\t\t\tconsole.log(data);\n");
      out.write("\t\t},error: function(){\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("};\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<button onclick=\"city_local_info();\">도시정보</button>\n");
      out.write("\r\n");
      out.write("<button onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lightning/lightningList.do'\">lightning.do</button>\r\n");
      out.write("\n");
      out.write("<input type=\"button\" value=\"동네친구 지도 확인\" onclick=\"searchMap();\" />\r\n");
      out.write("<input type=\"button\" value=\"동네친구찾기\" onclick=\"modaltest();\"/>\r\n");
      out.write("<input type=\"button\" value=\"동네친구찾기MODAL\" class=\"modal\" name=\"modal\" data-toggle=\"modal\" data-target=\"#searchfriend\" /> \r\n");
      out.write("<input type=\"text\" name=\"modalmember\" value=\"124\"/> <!-- 로그인된 회원의 멤버코드라고 가정 -->\r\n");
      out.write("\n");
      out.write("<button type=\"button\" class=\"btn btn-outline-success\"\n");
      out.write(" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/questionBoard/boardForm.do'\">질문 작성</button>\n");
      out.write(" <button type=\"button\" class=\"btn btn-outline-success\"\n");
      out.write(" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/questionBoard/questionBoard.do'\">질문 게시판 보기</button>\n");
      out.write("\t\t\t \n");
      out.write(" <button type=\"button\" class=\"btn btn-outline-success\"\n");
      out.write(" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/adminMain.do'\">관리자 메인 페이지</button>\n");
      out.write("\n");
      out.write("\r\n");
      out.write("\t<!-- 동네친구찾기버튼 눌렀을 때, 나타나는 MODAL -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"searchfriend\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("      <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("        \r\n");
      out.write("          <div class=\"modal-header\">\r\n");
      out.write("            <h5 class=\"modal-title\" id=\"exampleModalLabel\">동네친구찾기 추가정보 확인</h5>\r\n");
      out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("              <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/map/enrollFriend\" name=\"friend-frm\">\r\n");
      out.write("          <input type=\"text\" name=\"memberLoggedIn\" value=\"124\"/> <!-- 로그인된 회원의 멤버코드라고 가정 -->\r\n");
      out.write("          <div class=\"modal-body\"> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"\">\r\n");
      out.write("\t\t\t\t<textarea name=\"\" id=\"\" cols=\"60\" rows=\"3\" readonly>해당 서비스를 이용하기 위해서는 사용자정보 공개를 허용해야 합니다. 사용 하시겠습니까?</textarea>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"infocheck\" id=\"agree\" value=\"Y\" style=\"display:inline-block\" />\r\n");
      out.write("\t\t\t\t<label for=\"agree\">수락</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"\">\r\n");
      out.write("\t\t\t\t<p>회원님의 관심분야를 선택하여 주세요!</p>\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"interesting\" id=\"1\" value=\"음식\"/>\r\n");
      out.write("\t\t\t\t<label for=\"1\">음식</label>\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"interesting\" id=\"2\" value=\"여행\"/>\r\n");
      out.write("\t\t\t\t<label for=\"2\">여행</label>\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"interesting\" id=\"3\" value=\"술\"/>\r\n");
      out.write("\t\t\t\t<label for=\"3\">술</label>\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"interesting\" id=\"4\" value=\"영화\"/>\r\n");
      out.write("\t\t\t\t<label for=\"4\">영화</label>\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"interesting\" id=\"5\" value=\"기타\"/>\r\n");
      out.write("\t\t\t\t<label for=\"5\">기타</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t \r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"modal-footer\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-outline-success\" onclick=\"summitFrm2();\">확인</button>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-outline-success\" data-dismiss=\"modal\">취소</button>\r\n");
      out.write("          </div>\r\n");
      out.write("          </form>\r\n");
      out.write("         \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 동네친구찾기 MODAL End -->\r\n");
      out.write("\r\n");
      out.write("<br />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<input type=\"text\" name=\"position\" placeholder=\"검색하려는 장소를 입력하세요\"/>\r\n");
      out.write("<input type=\"button\" value=\"위치정보 확인\" onclick=\"findPosition();\" />\r\n");
      out.write("<div id=\"map\" style=\"width:700px;height:700px;\"></div>\r\n");
      out.write("<div id=\"infotest\"></div>\r\n");
      out.write("\r\n");
      out.write("<br />\r\n");
      out.write("\r\n");
      out.write("<input type=\"button\" value=\"동창찾기\" data-toggle=\"modal\" data-target=\"#searchModal\"/>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 로그인된 회원이 없을 경우 -->\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
