/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-07-22 05:39:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberEnroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1562298110696L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/Dropbox/workspace/Awesome/Awesome/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/Dropbox/workspace/Awesome/Awesome/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/Dropbox/workspace/Awesome/Awesome/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\" />\r\n");
      out.write("\t<title>회원가입</title>\r\n");
      out.write("\t<script src=\"https://www.google.com/recaptcha/api.js\" async defer></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.4.0.js\"></script>\r\n");
      out.write("\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js\" \r\n");
      out.write("\t\t\tintegrity=\"sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm\" crossorigin=\"anonymous\"/>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=gf3hncw6qx&submodules=geocoder\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.8.1/css/all.css\" \r\n");
      out.write("\t\tintegrity=\"sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf\" \r\n");
      out.write("\t\tcrossorigin=\"anonymous\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- 20190721 김용빈 -->\r\n");
      out.write("    <!-- Tiny Nice Confirmation Popup Plugin With jQuery - H-confirm-alert -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/H-confirm-alert.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/H-confirm-alert.css\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("\t\t#modalBody{ \r\n");
      out.write("\t\t\tdisplay : flex; \r\n");
      out.write("\t\t\tflex-direction : row;\r\n");
      out.write("\t\t\tjustify-content : space-between; \r\n");
      out.write("\t\t\talign-items : center;      \r\n");
      out.write("\t\t\talign-content : center;       \r\n");
      out.write("\t\t\tmax-width : 100%;     \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#modalBody span.guide {display:none;font-size: 12px; top:12px; right:10px;}\r\n");
      out.write("\t\t#modalBody span.ok{color:green;}\r\n");
      out.write("\t\t#modalBody span.error{color:red;}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#modalBody span.pwd {display:none;font-size: 12px; top:12px; right:10px;}\r\n");
      out.write("\t\t#modalBody span.error{color:red;}\r\n");
      out.write("\t\t.smsAuth {display:none;}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t#modalBody #modalList{\r\n");
      out.write("\t\t\t\tflex : 1 1 0; \r\n");
      out.write("\t\t\t\tmargin : auto; \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tdisplay : flex; \r\n");
      out.write("\t\t\t\tflex-direction : column;\r\n");
      out.write("\t\t\t\tjustify-content : space-between; \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t#modalBody #modalList .btn{\r\n");
      out.write("\t\t\t\t\tflex : 1 1 0; \r\n");
      out.write("\t\t\t\t\tmargin : auto;\r\n");
      out.write("\t\t\t\t\tmargin-top : 1%; \r\n");
      out.write("\t\t\t\t\twidth:100%;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t#modalBody .modal-body{\r\n");
      out.write("\t\t\t\tflex : 1 1 0; \r\n");
      out.write("\t\t\t\tmargin : auto; \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t #introduce{display:none;} \r\n");
      out.write("\t\t\t #introduceDiv{border:1px solid gray; border-radius:10px; padding:2%;}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.flex{\r\n");
      out.write("\t\t\t\t\tdisplay : flex; \r\n");
      out.write("            \t\tflex-direction : row;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t#introduceBtnDiv{text-align: right;}\r\n");
      out.write("\t</style> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t/*사진 미리보기\r\n");
      out.write("\t* FileReader객체을 이용해서 동적으로 파일을 읽어옴\r\n");
      out.write("\t* FileReader.result\r\n");
      out.write("\t* FileReader.readAsDataURL(file)\r\n");
      out.write("\t* FileReader.onload\r\n");
      out.write("\t*/\r\n");
      out.write("\t\tfunction loadImg(f){  //f= input:file 태그\r\n");
      out.write("\t\t\tconsole.log(f.files); //FileList\r\n");
      out.write("\t\t\tconsole.log(f.files[0]); // File 실제 업로드한 파일\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(f.files && f.files[0]){ //undefined시에 false로 인식함 (js에서만 이런식으로 동작)\r\n");
      out.write("\t\t\t\tvar reader = new FileReader();\r\n");
      out.write("\t\t\t\t//파일 읽기메소드 호출. 읽기완료하면 onload에 등록된 함수을 호출\r\n");
      out.write("\t\t\t\t reader.readAsDataURL(f.files[0]);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\treader.onload = function(){\r\n");
      out.write("\t\t\t\t\t//result속성에는 파일컨텐츠가 담겨있음.\r\n");
      out.write("\t\t\t\t\t $(\"#profileImg\").attr(\"src\",reader.result);\r\n");
      out.write("\t\t\t\t\t //$(\"#profileUp\").hide();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t//스마트 에디터 연결(자기소개 작성)\r\n");
      out.write("\t\tfunction introducePopup(){\r\n");
      out.write("\t\t\tvar pop = window.open(\"/awesome/member/smartEditor\",\"pop\",\"width=610,height=380, scrollbars=yes, resizable=yes\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\t * 주소검색\r\n");
      out.write("\t\t*/\r\n");
      out.write("\t    \tfunction goPopup(){\r\n");
      out.write("\t    \t\t// 주소검색을 수행할 팝업 페이지를 호출합니다.\r\n");
      out.write("\t    \t\t// 호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(http://www.juso.go.kr/addrlink/addrLinkUrl.do)를 호출하게 됩니다.\r\n");
      out.write("\t    \t\tvar pop = window.open(\"/awesome/member/jusoPopup\",\"pop\",\"width=570,height=420, scrollbars=yes, resizable=yes\");\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tfunction jusoCallBack(roadFullAddr,roadAddrPart1,addrDetail,roadAddrPart2,engAddr, jibunAddr, zipNo, admCd, rnMgtSn, bdMgtSn,detBdNmList,bdNm,bdKdcd,siNm,sggNm,emdNm,liNm,rn,udrtYn,buldMnnm,buldSlno,mtYn,lnbrMnnm,lnbrSlno,emdNo){\r\n");
      out.write("\t    \t\t// 팝업페이지에서 주소입력한 정보를 받아서, 현 페이지에 정보를 등록합니다.\r\n");
      out.write("\t    \t\t$(\"#postNo\").val(zipNo);\r\n");
      out.write("\t    \t\t$(\"#roadAddress\").val(roadAddrPart1);\r\n");
      out.write("\t    \t\t$(\"#address\").val(jibunAddr);\r\n");
      out.write("\t    \t\t$(\"#detailAddress\").val(addrDetail);\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t\t    \t/* 회원가입시 주소받을 때 사용자 지번주소의 x좌표 , y좌표 구하기 시작 */\r\n");
      out.write("\t\t    \tnaver.maps.Service.geocode({\r\n");
      out.write("\t\t    \t    address: jibunAddr\r\n");
      out.write("\t\t    \t}, function(status, response) {\r\n");
      out.write("\t\t    \t    if (status !== naver.maps.Service.Status.OK) {\r\n");
      out.write("\t\t    \t        return alert('Something wrong!');\r\n");
      out.write("\t\t    \t    }\r\n");
      out.write("\t\r\n");
      out.write("\t\t    \t    var result = response.result, // 검색 결과의 컨테이너\r\n");
      out.write("\t\t    \t        items = result.items; // 검색 결과의 배열\r\n");
      out.write("\t\t    \t\t\r\n");
      out.write("\t\t    \t        $(\"#placeLat\").val(items[0].point.x);\r\n");
      out.write("\t\t    \t        $(\"#placeLng\").val(items[0].point.y);\r\n");
      out.write("\t\t    \t        \tconsole.log(items);\r\n");
      out.write("\t\t    \t    \t\tconsole.log(items[0].point.x);\r\n");
      out.write("\t\t    \t    \t\tconsole.log(items[0].point.y);\r\n");
      out.write("\t\t    \t     \r\n");
      out.write("\t\t    \t});\r\n");
      out.write("\t\t    \t/* 회원가입시 주소받을 때 사용자 지번주소의 x좌표 , y좌표 구하기 끝  */\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \t\r\n");
      out.write("\t  /*회원가입 유효성검사*/\r\n");
      out.write("\r\n");
      out.write("\t\tfunction regExpTest(v,y,str){\r\n");
      out.write("\t\t    var id = $(\"#\"+y).val();\r\n");
      out.write("\r\n");
      out.write("\t\t    if(!v.test(id)){\r\n");
      out.write("\t\t    \t$.confirm.show({\r\n");
      out.write("\t\t\t\t\t  \"message\": str,\r\n");
      out.write("\t\t\t\t\t  \"yes\": function (){\r\n");
      out.write("\t\t\t\t\t\t  $(\"#enrollMemberId\").focus();\r\n");
      out.write("\t    \t\t\t\t  $(\"#idDuplicateCheck\").val(0);\r\n");
      out.write("\t\t\t\t\t  },\r\n");
      out.write("\t\t\t\t\t  \"hideNo\":true,\r\n");
      out.write("\t\t\t\t\t  \"type\":\"warning\" // default or success, danger, warning\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t        return false;\r\n");
      out.write("\t\t    }else{\r\n");
      out.write("\t\t        return true;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t function nullChk(v,y,str){\r\n");
      out.write("\t\t    var id = $(\"#\"+y).val();\r\n");
      out.write("\r\n");
      out.write("\t\t    if(v.test(id)){\r\n");
      out.write("\t\t    \t$.confirm.show({\r\n");
      out.write("\t\t\t\t\t  \"message\": str,\r\n");
      out.write("\t\t\t\t\t  \"yes\": function (){\r\n");
      out.write("\t\t\t\t\t\t  $(\"#enrollMemberId\").focus();\r\n");
      out.write("\t    \t\t\t\t  $(\"#idDuplicateCheck\").val(0);\r\n");
      out.write("\t\t\t\t\t  },\r\n");
      out.write("\t\t\t\t\t  \"hideNo\":true,\r\n");
      out.write("\t\t\t\t\t  \"type\":\"warning\" // default or success, danger, warning\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t        return false;\r\n");
      out.write("\t\t    }else{\r\n");
      out.write("\t\t        return true;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\r\n");
      out.write("\t  \tfunction enrollValidate(){\r\n");
      out.write("\t  \t\tconsole.log(\"!!start!!!\");\r\n");
      out.write("\t  \t\tresult=false;\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/VerifyRecaptcha',\r\n");
      out.write("                type: 'post',\r\n");
      out.write("                async: false,\r\n");
      out.write("                data: {\r\n");
      out.write("                \t\r\n");
      out.write("                    recaptcha: $(\"#g-recaptcha-response\").val()\r\n");
      out.write("                },\r\n");
      out.write("                success: function(data) {\r\n");
      out.write("                    switch (data) {\r\n");
      out.write("                        case 0:\r\n");
      out.write("                        \tresult=true;\r\n");
      out.write("                            break;\r\n");
      out.write("\r\n");
      out.write("                        case 1:\r\n");
      out.write("                        \tresult=false;\r\n");
      out.write("                            $.confirm.show({\r\n");
      out.write("         \t\t\t\t\t\t  \"message\": \"자동 가입 방지 봇을 확인 한뒤 진행 해 주세요.\",\r\n");
      out.write("         \t\t\t\t\t\t  \"yes\": function (){\r\n");
      out.write("         \t\t\t\t\t\t  },\r\n");
      out.write("         \t\t\t\t\t\t  \"hideNo\":true,\r\n");
      out.write("         \t\t\t\t\t\t  \"type\":\"warning\" // default or success, danger, warning\r\n");
      out.write("         \t\t\t\t\t\t})\r\n");
      out.write("                            break;\r\n");
      out.write("\r\n");
      out.write("                        default:\r\n");
      out.write("                        \tresult=false;\r\n");
      out.write("                            $.confirm.show({\r\n");
      out.write("       \t\t\t\t\t\t  \"message\": \"자동 가입 방지 봇을 실행 하던 중 오류가 발생 했습니다. [Error bot Code : \" + Number(data) + \"]\",\r\n");
      out.write("       \t\t\t\t\t\t  \"yes\": function (){\r\n");
      out.write("       \t\t\t\t\t\t  },\r\n");
      out.write("       \t\t\t\t\t\t  \"hideNo\":true,\r\n");
      out.write("       \t\t\t\t\t\t  \"type\":\"warning\" // default or success, danger, warning\r\n");
      out.write("       \t\t\t\t\t\t})\r\n");
      out.write("                        \tbreak;\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            console.log(\"!!!!!\"+result);\r\n");
      out.write("\t  \t\tif(!result){\r\n");
      out.write("\t  \t\t\treturn false;\r\n");
      out.write("\t  \t\t}\r\n");
      out.write("            \r\n");
      out.write("\t\t\tif($(\"#idDuplicateCheck\").val()!=1 ){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.confirm.show({\r\n");
      out.write("\t\t\t\t\t\t  \"message\": \"아이디 중복 여부 확인하세요.\",\r\n");
      out.write("\t\t\t\t\t\t  \"yes\": function (){\r\n");
      out.write("\t\t\t\t\t\t  },\r\n");
      out.write("\t\t\t\t\t\t  \"hideNo\":true,\r\n");
      out.write("\t\t\t\t\t\t  \"type\":\"warning\" // default or success, danger, warning\r\n");
      out.write("\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#memberId\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($(\"#nickDuplicateCheck\").val()!=1 ){\r\n");
      out.write("\t\t\t\t$.confirm.show({\r\n");
      out.write("\t\t\t\t\t  \"message\": \"닉네임 중복 여부 확인하세요.\",\r\n");
      out.write("\t\t\t\t\t  \"yes\": function (){\r\n");
      out.write("\t\t\t\t\t  },\r\n");
      out.write("\t\t\t\t\t  \"hideNo\":true,\r\n");
      out.write("\t\t\t\t\t  \"type\":\"warning\" // default or success, danger, warning\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t$(\"#nickDuplicateCheck\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($(\"#smsAuthChk\").val()!=1 ){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.confirm.show({\r\n");
      out.write("\t\t\t\t\t  \"message\": \"핸드폰 인증이 필요합니다.\",\r\n");
      out.write("\t\t\t\t\t  \"yes\": function (){\r\n");
      out.write("\t\t\t\t\t  },\r\n");
      out.write("\t\t\t\t\t  \"hideNo\":true,\r\n");
      out.write("\t\t\t\t\t  \"type\":\"warning\" // default or success, danger, warning\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#phoneAuth\").focus();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//return false; //운영시에 주석해제\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tconsole.log(\"???????????\");\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("      $(function(){\r\n");
      out.write("    \t  $(\"#phoneAuthBtn\").on(\"click\",function(){\r\n");
      out.write("      \t\tvar userPhoneNumber = $(\"#phoneAuth\").val();\r\n");
      out.write("\t\t\tif($(\"#phoneAuth\").val().length<10 ){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.confirm.show({\r\n");
      out.write("\t\t\t\t\t\t  \"message\": \"연락처을 -을 제외하고 입력하세요\",\r\n");
      out.write("\t\t\t\t\t\t  \"yes\": function (){\r\n");
      out.write("\t\t\t\t\t\t  },\r\n");
      out.write("\t\t\t\t\t\t  \"hideNo\":true,\r\n");
      out.write("\t\t\t\t\t\t  \"type\":\"warning\" // default or success, danger, warning\r\n");
      out.write("\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#phoneAuth\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("      \t\t\r\n");
      out.write("      \t\t$(\".smsAuth\").show(400);//운영시에 삭제\r\n");
      out.write("\t\t\t$(\"#smsAuthBtn\").show(400);//운영시에 삭제\r\n");
      out.write("      \t\t\r\n");
      out.write("      \t\t/*  $.ajax({        //운영시에 주석해제\r\n");
      out.write("      \t\t\t url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/sendSMS\", \r\n");
      out.write("      \t\t\ttype: \"POST\",\r\n");
      out.write("      \t\t\tdata: \"userPhoneNumber=\"+userPhoneNumber,\r\n");
      out.write("\t\t\t\tdataType : 'text',\r\n");
      out.write("      \t\t\tsuccess : function(data){\r\n");
      out.write("      \t\t\t\t$(\".smsAuth\").show(400);\r\n");
      out.write("      \t\t\t\t$(\"#smsAuthBtn\").hide(400);\r\n");
      out.write("      \t\t\t\talert(data);\r\n");
      out.write("      \t\t\t},\r\n");
      out.write("      \t\t\terror: function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("      \t\t\t\tconsole.log(\"ajax처리실패! : \"+jqxhr.status);\r\n");
      out.write("      \t\t\t\tconsole.log(jqxhr);\r\n");
      out.write("      \t\t\t\tconsole.log(textStatus);\r\n");
      out.write("      \t\t\t\tconsole.log(errorThrown);\r\n");
      out.write("      \t\t\t}\r\n");
      out.write("      \t\t});  */\r\n");
      out.write("    \t  });\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  $(\"#smsAuthBtn\").on(\"click\",function(){\r\n");
      out.write("    \t\t  \r\n");
      out.write("    \t\t  var authNum = $(\"#smsAuth\").val();\r\n");
      out.write("    \t\t  \r\n");
      out.write(" \t\t\t $.ajax({ \r\n");
      out.write("\t\t\t\t url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/chkSmsAuth\", \r\n");
      out.write("\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\tdata: \"authNum=\"+authNum,\r\n");
      out.write("\t\t\t\tdataType : 'text',\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tif(data ==\"success\"){\r\n");
      out.write("\t\t\t\t\t\t$.confirm.show({\r\n");
      out.write("\t\t\t\t\t\t\t  \"message\": \"문자인증을 완료하였습니다.\",\r\n");
      out.write("\t\t\t\t\t\t\t  \"yes\": function (){\r\n");
      out.write("\t\t\t\t\t\t\t  },\r\n");
      out.write("\t\t\t\t\t\t\t  \"hideNo\":true,\r\n");
      out.write("\t\t\t\t\t\t\t  \"type\":\"warning\" // default or success, danger, warning\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#smsAuth\").val(\"\").hide(400);\r\n");
      out.write("\t\t\t\t\t\t$(\"#smsAuthBtn\").hide(400);\r\n");
      out.write("\t\t\t\t\t\t//$(\".smsAuth\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#smsAuthChk\").val(1);\r\n");
      out.write("\t\t\t\t\t\t//$(\"#phoneAuthBtn\").hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(data ==\"fail\"){\r\n");
      out.write("\t\t\t\t\t\t$.confirm.show({\r\n");
      out.write("\t\t\t\t\t\t\t  \"message\": \"인증을 실패하였습니다. 인증번호을 확인하세요\",\r\n");
      out.write("\t\t\t\t\t\t\t  \"yes\": function (){\r\n");
      out.write("\t\t\t\t\t\t\t  },\r\n");
      out.write("\t\t\t\t\t\t\t  \"hideNo\":true,\r\n");
      out.write("\t\t\t\t\t\t\t  \"type\":\"warning\" // default or success, danger, warning\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t$(\"#smsAuthChk\").val(0);\r\n");
      out.write("\t\t\t\t\t\t$(\"#smsAuth\").val(\"\").focus();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"ajax처리실패! : \"+jqxhr.status);\r\n");
      out.write("\t\t\t\t\tconsole.log(jqxhr);\r\n");
      out.write("\t\t\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\t\t\tconsole.log(errorThrown);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});  \r\n");
      out.write("\t\t  });\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  \r\n");
      out.write("    \t$(\"#idDuplicateCheckBtn\").on(\"click\",function(){\r\n");
      out.write("    \t\tvar memberId = $(\"#enrollMemberId\").val().trim();\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t    var regExp1 = /^[a-z][a-z\\d]{3,11}/;\r\n");
      out.write("    \t    var regExp2 = /[0-9]/;\r\n");
      out.write("    \t    var regExpId = /\\s/;\r\n");
      out.write("    \t    var regEmail = /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$/i;\r\n");
      out.write("\r\n");
      out.write("    \t    var bool = regExpTest(regEmail,\"enrollMemberId\",\"사용자 아이디는 이메일형식으로 입력하세요\");\r\n");
      out.write("    \t    if(!bool){\r\n");
      out.write("    \t    \t$(\"#enrollMemberId\").focus();\r\n");
      out.write("    \t    \treturn;\r\n");
      out.write("    \t    }\r\n");
      out.write("    \t    \r\n");
      out.write("    \t    var bool = nullChk(regExpId,\"enrollMemberId\",\"아이디에는 공백이포함되면 안됩니다.\");\r\n");
      out.write("    \t    if(!bool){\r\n");
      out.write("    \t    \t$(\"#enrollMemberId\").focus();\r\n");
      out.write("    \t    \treturn;\r\n");
      out.write("    \t    }\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t$.ajax({ \r\n");
      out.write("    \t\t\t url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/checkIdDuplicate.do\", \r\n");
      out.write("    \t\t\tdata:{memberId: memberId},\r\n");
      out.write("    \t\t\tsuccess : function(data){\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\tif(data.isUsable == true){\r\n");
      out.write("    \t\t\t\t\t$.confirm.show({\r\n");
      out.write("\t\t\t\t\t\t\t  \"message\": \"사용가능한 아이디입니다.\",\r\n");
      out.write("\t\t\t\t\t\t\t  \"yes\": function (){\r\n");
      out.write("\t\t\t\t\t\t\t\t  $(\"#nickName\").focus();\r\n");
      out.write("\t\t\t    \t\t\t\t  $(\"#idDuplicateCheck\").val(1);\r\n");
      out.write("\t\t\t\t\t\t\t  },\r\n");
      out.write("\t\t\t\t\t\t\t  \"hideNo\":true,\r\n");
      out.write("\t\t\t\t\t\t\t  \"type\":\"warning\" // default or success, danger, warning\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t\t$.confirm.show({\r\n");
      out.write("    \t\t\t\t\t\t  \"message\": \"사용불가한 아이디입니다 \",\r\n");
      out.write("    \t\t\t\t\t\t  \"yes\": function (){\r\n");
      out.write("    \t\t\t\t\t\t\t  $(\"#enrollMemberId\").focus();\r\n");
      out.write("    \t\t    \t\t\t\t  $(\"#idDuplicateCheck\").val(0);\r\n");
      out.write("    \t\t\t\t\t\t  },\r\n");
      out.write("    \t\t\t\t\t\t  \"hideNo\":true,\r\n");
      out.write("    \t\t\t\t\t\t  \"type\":\"warning\" // default or success, danger, warning\r\n");
      out.write("    \t\t\t\t\t\t})\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t},\r\n");
      out.write("    \t\t\terror: function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("    \t\t\t\tconsole.log(\"ajax처리실패! : \"+jqxhr.status);\r\n");
      out.write("    \t\t\t\tconsole.log(jqxhr);\r\n");
      out.write("    \t\t\t\tconsole.log(textStatus);\r\n");
      out.write("    \t\t\t\tconsole.log(errorThrown);\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t});\r\n");
      out.write("    \t\r\n");
      out.write("    \t$(\"#nickDuplicateCheckBtn\").on(\"click\",function(){\r\n");
      out.write("    \t\tvar nickName = $(\"#nickName\").val().trim();\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t    var regExp1 = /^.{4,11}/;\r\n");
      out.write("    \t    var regExp2 = /[0-9]/;\r\n");
      out.write("    \t    var regExpId = /\\s/;\r\n");
      out.write("\r\n");
      out.write("    \t    var bool = regExpTest(regExp1,\"nickName\",\"사용자 닉네임은 4~11자로 입력하세요\");\r\n");
      out.write("    \t    if(!bool){\r\n");
      out.write("    \t    \t$(\"#nickName\").focus();\r\n");
      out.write("    \t    \treturn;\r\n");
      out.write("    \t    }\r\n");
      out.write("\r\n");
      out.write("    \t    var bool = nullChk(regExpId,\"nickName\",\"닉네임에는 공백이포함되면 안됩니다.\");\r\n");
      out.write("    \t    if(!bool){\r\n");
      out.write("    \t    \t$(\"#nickName\").focus();\r\n");
      out.write("    \t    \treturn;\r\n");
      out.write("    \t    }\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t$.ajax({ \r\n");
      out.write("    \t\t\t url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/checkNickNameDuplicate.do\", \r\n");
      out.write("    \t\t\tdata:{nickName: nickName},\r\n");
      out.write("    \t\t\tsuccess : function(data){\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\tif(data.isUsable == true){\r\n");
      out.write("    \t\t\t\t\t$.confirm.show({\r\n");
      out.write("  \t\t\t\t\t\t  \"message\": \"사용 가능 한 닉네임입니다.\",\r\n");
      out.write("  \t\t\t\t\t\t  \"yes\": function (){\r\n");
      out.write("  \t\t\t\t\t\t\t$(\"#password_\").focus();\r\n");
      out.write("  \t    \t\t\t\t\t$(\"#nickDuplicateCheck\").val(1);\r\n");
      out.write("  \t\t\t\t\t\t  },\r\n");
      out.write("  \t\t\t\t\t\t  \"hideNo\":true,\r\n");
      out.write("  \t\t\t\t\t\t  \"type\":\"warning\" // default or success, danger, warning\r\n");
      out.write("  \t\t\t\t\t\t})\r\n");
      out.write("    \t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t\t$.confirm.show({\r\n");
      out.write("   \t\t\t\t\t\t  \"message\": \"사용 불가 한 닉네임입니다.\",\r\n");
      out.write("   \t\t\t\t\t\t  \"yes\": function (){\r\n");
      out.write("   \t\t    \t\t\t\t\t$(\"#nickName\").focus();\r\n");
      out.write("   \t\t    \t\t\t\t\t$(\"#nickDuplicateCheck\").val(0);\r\n");
      out.write("   \t\t\t\t\t\t  },\r\n");
      out.write("   \t\t\t\t\t\t  \"hideNo\":true,\r\n");
      out.write("   \t\t\t\t\t\t  \"type\":\"warning\" // default or success, danger, warning\r\n");
      out.write("   \t\t\t\t\t\t})\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t},\r\n");
      out.write("    \t\t\terror: function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("    \t\t\t\tconsole.log(\"ajax처리실패! : \"+jqxhr.status);\r\n");
      out.write("    \t\t\t\tconsole.log(jqxhr);\r\n");
      out.write("    \t\t\t\tconsole.log(textStatus);\r\n");
      out.write("    \t\t\t\tconsole.log(errorThrown);\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t});\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t$(\"#password_\").blur(function(){\r\n");
      out.write("    \t\t$(\".pwd.error.ori\").hide();\r\n");
      out.write("    \t\tif($(\"#password_\").val().length<6){\r\n");
      out.write("    \t\t\t$(\".pwd.error.ori\").show();\r\n");
      out.write("    \t\t\t$(\"#password_\").focus();\r\n");
      out.write("    \t\t\treturn;\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t});\r\n");
      out.write("    \t\r\n");
      out.write("    \t$(\"#passwordChk\").blur(function(){\r\n");
      out.write("    \t\tvar p1=$(\"#password_\").val(), p2=$(\"#passwordChk\").val();\r\n");
      out.write("    \t\tif(p1!=p2){\r\n");
      out.write("\t\t\t\t$(\".pwd.error.chk\").show();\r\n");
      out.write("    \t\t\t$(\"#password_\").focus();\r\n");
      out.write("    \t\t\treturn;\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t$(\".pwd.error.chk\").hide();\r\n");
      out.write("    \t});\r\n");
      out.write("    \t\r\n");
      out.write("    \t$(\"#phoneAuth\").blur(function(){\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tvar phoneNo = $(\"#phoneAuth\").val();\r\n");
      out.write("    \t\tvar findStr = \"-\";\r\n");
      out.write("\r\n");
      out.write("    \t\tif (phoneNo.indexOf(findStr) != -1) {\r\n");
      out.write("    \t\t  $(\".pwd.error.phone\").show();\r\n");
      out.write("    \t\t  $(\"#phoneAuth\").focus();\r\n");
      out.write("    \t\t}else{\r\n");
      out.write("    \t\t\t$(\".pwd.error.phone\").hide();\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t});\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t$(\"[name=upfile]\").on(\"change\",function(){\r\n");
      out.write("    \t\t//사용자가 파일입력을 취소한경우\r\n");
      out.write("    \t\tif($(this).prop('files')[0]===undefined){\r\n");
      out.write("    \t\t\t$(this).next(\".custom-file-label\").html(\"사진을 선택하세요\");\r\n");
      out.write("    \t\t\treturn;\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t// var fileName = $(this).val();   //C:\\\\fakepath\\\\'파일명'\r\n");
      out.write("    \t\tvar fileName = $(this).prop('files')[0].name;\r\n");
      out.write("    \t\tconsole.log(fileName);\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t$(this).next(\".custom-file-label\").html(fileName);\r\n");
      out.write("    \t})\r\n");
      out.write("\r\n");
      out.write("    });\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h5 class=\"modal-title\" id=\"exampleModalLabel\">회원 가입</h5>\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("            <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("\t          \r\n");
      out.write("       <div id=\"modalBody\">\r\n");
      out.write("        <!-- : https://getbootstrap.com/docs/4.1/components/forms/#overview -->\r\n");
      out.write("        <form name=\"memberEnrollFrm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/memberEnrollEnd.do\" \r\n");
      out.write("        \t\tenctype=\"multipart/form-data\" method=\"post\" onsubmit=\"return enrollValidate();\">\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("        \t<div id=\"img-viewer-container\">\r\n");
      out.write("\t\t\t\t<img id=\"profileImg\" width=200/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<div class=\"flex\">\r\n");
      out.write("            \t\t<input type=\"email\" class=\"form-control\" name=\"memberId\" id=\"enrollMemberId\" placeholder=\"이메일 형식 아이디\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("             \t\t<button type=\"button\" class=\"btn btn-outline-success\" id=\"idDuplicateCheckBtn\">중복체크</button>\r\n");
      out.write("\t\t  \t\t<input type=\"hidden\" id=\"idDuplicateCheck\" value=\"0\"/>\r\n");
      out.write("\t\t  \t</div>\r\n");
      out.write("              <br />\r\n");
      out.write("             <div class=\"flex\">\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" name=\"nickName\" id=\"nickName\" placeholder=\"별명(4~11자 사이로 입력)\" required>\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-outline-success\" id=\"nickDuplicateCheckBtn\">중복체크</button>\r\n");
      out.write("              <input type=\"hidden\" id=\"nickDuplicateCheck\" value=\"0\"/>\r\n");
      out.write("             </div>\r\n");
      out.write("              <br />\r\n");
      out.write("              <input type=\"password\" class=\"form-control\" name=\"password\" id=\"password_\" placeholder=\"비밀번호\" required>\r\n");
      out.write("              <span class=\"pwd error ori\">패스워드는 6글자이상 입력하세요</span>\r\n");
      out.write("              <br />\r\n");
      out.write("              <input type=\"password\" class=\"form-control\" name=\"passwordChk\" id=\"passwordChk\" placeholder=\"비밀번호 확인\" required>\r\n");
      out.write("              <span class=\"pwd error chk\">패스워드가 일치하지 않습니다.</span>\r\n");
      out.write("              <br />\r\n");
      out.write("\t            <div id=\"profileUp\" class=\"input-group mb-3\" style=\"padding:0px;\">\r\n");
      out.write("\t\t\t\t  <div class=\"custom-file\">\r\n");
      out.write("\t\t\t\t    <input type=\"file\" class=\"form-control custom-file-input\" name=\"upfile\" id=\"upfile\" onchange=\"loadImg(this);\">\r\n");
      out.write("\t\t\t\t    <label class=\"custom-file-label\" for=\"upfile\"><i class=\"far fa-user\"> 프로필 사진 등록</i></label>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("              <br />\r\n");
      out.write("              \r\n");
      out.write("              <input type=\"text\" class=\"form-control\" name=\"memberName\" placeholder=\"이름\" required>\r\n");
      out.write("              <br />\r\n");
      out.write("              <input type=\"date\" class=\"form-control\" name=\"birthday\" placeholder=\"생년월일\" required>\r\n");
      out.write("              <br />\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"flex\">\r\n");
      out.write("\t            <div class=\"custom-control custom-radio\">\r\n");
      out.write("\t\t\t\t  <input type=\"radio\" id=\"gender_m\" name=\"gender\" class=\"custom-control-input\" value=\"M\" checked required>\r\n");
      out.write("\t\t\t\t  <label class=\"custom-control-label\" for=\"gender_m\">male</label>\r\n");
      out.write("\t\t\t\t</div> &nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<div class=\"custom-control custom-radio\">\r\n");
      out.write("\t\t\t\t  <input type=\"radio\" id=\"gender_f\" name=\"gender\" class=\"custom-control-input\" value=\"F\" required>\r\n");
      out.write("\t\t\t\t  <label class=\"custom-control-label\" for=\"gender_f\">female</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"flex\">\r\n");
      out.write("\t              <input type=\"tel\" class=\"form-control\" name=\"phone\" id=\"phoneAuth\" placeholder=\"연락처, '-'을 제외하고 입력하세요\" required>\r\n");
      out.write("\t              <button type=\"button\" class=\"btn btn-outline-success\" id=\"phoneAuthBtn\">인증문자 발송</button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"flex\">\r\n");
      out.write("\t              <input type=\"number\" class=\"form-control smsAuth\" name=\"smsAuthInput\" id=\"smsAuth\" placeholder=\"인증문자 입력\">\r\n");
      out.write("\t              <button type=\"button\" class=\"btn btn-outline-success smsAuth\" id=\"smsAuthBtn\">확인</button>\r\n");
      out.write("\t              <input type=\"hidden\" id=\"smsAuthChk\" value=\"0\"/>\r\n");
      out.write("              </div>\r\n");
      out.write("              <br />\r\n");
      out.write("              <div class=\"flex\">\r\n");
      out.write("\t              <input type=\"number\" class=\"form-control\" name=\"postNo\" id=\"postNo\" placeholder=\"우편번호\" required readonly>\r\n");
      out.write("\t              <button type=\"button\" class=\"btn btn-outline-success\" onclick=\"goPopup()\">검색</button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" name=\"roadAddress\" id=\"roadAddress\" placeholder=\"주소\" required readonly>\r\n");
      out.write("              <input type=\"hidden\" class=\"form-control\" name=\"address\" id=\"address\" placeholder=\"지번주소\" required readonly>\r\n");
      out.write("              <input type=\"hidden\" class=\"form-control\" name=\"placeLat\" id=\"placeLat\" placeholder=\"위도\" required readonly>\r\n");
      out.write("              <input type=\"hidden\" class=\"form-control\" name=\"placeLng\" id=\"placeLng\" placeholder=\"경도\" required readonly>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" name=\"detailAddress\" id=\"detailAddress\" placeholder=\"상세주소\" required readonly>\r\n");
      out.write("              <br />\r\n");
      out.write("<!--               <input type=\"checkbox\" name=\"blindDateOpen\" id=\"blindDateOpen\" value=\"Y\"/>\r\n");
      out.write("              <label for=\"blindDateOpen\">소개팅공개여부</label>\r\n");
      out.write("              <br />\r\n");
      out.write("              <input type=\"checkbox\" name=\"friendOpen\" id=\"friendOpen\" value=\"Y\"/>\r\n");
      out.write("              <label for=\"friendOpen\">친구공개여부</label>\r\n");
      out.write("              <br />\r\n");
      out.write("              <input type=\"checkbox\" name=\"searchOpen\" id=\"searchOpen\" value=\"Y\"/>\r\n");
      out.write("\t\t\t\t<label for=\"searchOpen\">검색공개여부</label>\r\n");
      out.write("              <br /> -->\r\n");
      out.write(" \t\t\t <textarea name=\"introduce\" id=\"introduce\" cols=\"30\" rows=\"5\" style=\"resize: none\" placeholder=\"자기소개\" required>\r\n");
      out.write("\t\t\t</textarea>\r\n");
      out.write("\t\t\t<div id=\"introduceDiv\" name=\"introduceDiv\">\r\n");
      out.write("\t\t\t\t<p>안녕하세요!~AWESOME입니다.<br>아래버튼을 눌러 자기소개을 작성하세요!</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"introduceBtnDiv\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-outline-success\" id=\"introduceBtn\" onclick=\"introducePopup()\">자기소개 작성</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t<div class=\"g-recaptcha\" data-sitekey=\"6LfzMK0UAAAAAKN5D-f_R8j35H8xSDPgbxDBBReO\"></div>\r\n");
      out.write("\t\t\t<input type=\"hidden\" class=\"form-control\" name=\"recaptcha\" id=\"recaptcha\" readonly>\r\n");
      out.write("        </div>\r\n");
      out.write("\t       <div class=\"modal-footer\">\r\n");
      out.write("\t         <button type=\"submit\" class=\"btn btn-outline-success\" >확인</button>\r\n");
      out.write("\t         <button type=\"button\" class=\"btn btn-outline-success\" data-dismiss=\"modal\">취소</button>\r\n");
      out.write("\t       </div>\r\n");
      out.write("       </form>\r\n");
      out.write("       </div>\r\n");
      out.write("\t\t <!-- 회원가입 모달 끝 -->\r\n");
      out.write("\t\t \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
