/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-07-22 02:14:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.awesome.member.model.vo.Member;

public final class memberInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1562298110696L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/Dropbox/workspace/Awesome/Awesome/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/Dropbox/workspace/Awesome/Awesome/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/Dropbox/workspace/Awesome/Awesome/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.awesome.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Awesome", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.4.0.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.8.1/css/all.css\" \r\n");
      out.write("    \tintegrity=\"sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf\" crossorigin=\"anonymous\"/>\r\n");
      out.write("\t  <!-- bootstrap -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" \r\n");
      out.write("        integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js\" integrity=\"sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t#container{\r\n");
      out.write("\t\t\tdisplay : flex; \r\n");
      out.write("            flex-direction : row;\r\n");
      out.write("            \r\n");
      out.write("           \theight:500px;\r\n");
      out.write("           \twidth :1000px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t#item-head{\r\n");
      out.write("           \t\tflex : 1; \r\n");
      out.write("           \t\tmargin : auto;\r\n");
      out.write("           \t\t\r\n");
      out.write("           \t\theight:100%;\r\n");
      out.write("           \t\t\r\n");
      out.write("           \t\tdisplay : flex; \r\n");
      out.write("            \tflex-direction : column;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t#item-head-main{\r\n");
      out.write("\t           \t\tflex : 1; \r\n");
      out.write("\t           \t\tmargin : auto;\r\n");
      out.write("\t           \t\t\r\n");
      out.write("\t           \t\t\r\n");
      out.write("\t           \t\twidth:100%;\r\n");
      out.write("\t           \t\theight:100%;\r\n");
      out.write("\t           \t\t\r\n");
      out.write("\t           \t\tdisplay : flex; \r\n");
      out.write("               \t\tflex-direction : column;\r\n");
      out.write("\t           \t\talign-items : center;   \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t#item-list{\r\n");
      out.write("\t\t\t\t\t\tlist-style-type: none;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t#profile{\r\n");
      out.write("\t\t\t\t\t\tflex : 4; \r\n");
      out.write("\t           \t\t\tmargin : auto;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tmargin : 2%;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\toverflow:hidden;\r\n");
      out.write("        \t\t\t\tborder-radius: 70%;\r\n");
      out.write("        \t\t\t\twidth:50%;\r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t#item-head-items{\r\n");
      out.write("\t           \t\tflex : 3; \r\n");
      out.write("\t           \t\tmargin : 10%;\r\n");
      out.write("\t           \t\r\n");
      out.write("\t           \t\theight:100%;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t#item-body{\r\n");
      out.write("           \t\tflex : 4; \r\n");
      out.write("           \t\tmargin : auto;\r\n");
      out.write("           \t\t\r\n");
      out.write("           \t\t/* overflow: scroll; */\r\n");
      out.write("           \t\theight:100%;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write(" \t\t\t#item-body::-webkit-scrollbar { \r\n");
      out.write("\t\t\t    display: none; \r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(\"#memberInfoUpdate\").on(\"click\",function(){\r\n");
      out.write("\t      \t\t  $.ajax({\r\n");
      out.write("\t      \t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/memberInfoUpdate.do\", \r\n");
      out.write("\t      \t\t\tsuccess : function(data){\r\n");
      out.write("\t      \t\t\t\t$(\"#item-body\").html(data);\r\n");
      out.write("\t      \t\t\t},\r\n");
      out.write("\t      \t\t\terror: function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("\t      \t\t\t\tconsole.log(\"ajax처리실패! : \"+jqxhr.status);\r\n");
      out.write("\t      \t\t\t\tconsole.log(jqxhr);\r\n");
      out.write("\t      \t\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t      \t\t\t\tconsole.log(errorThrown);\r\n");
      out.write("\t      \t\t\t}\r\n");
      out.write("\t      \t\t});\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t  $(\"#info-head li\").on(\"click\",function(){\r\n");
      out.write("    \t\t //$(\"#\"+$(this)[0].className).slideToggle(1000, 'easeInBack');\r\n");
      out.write("    \t\t  $(\"#\"+$(this)[0].className).show(1000);\r\n");
      out.write("    \t  });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#memberInfoUpdate\").trigger(\"click\");\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"item-head\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div id=\"item-head-main\">\r\n");
      out.write("\t\t\t\t<div id=\"profile\">\r\n");
      out.write("\t\t\t\t\t<img id=\"profileImg\" width=100% src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/upload/member/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.renamedProfile }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"memberNickName\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.nickName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"item-head-items\">\r\n");
      out.write("\t\t\t\t<ul id=\"item-list\">\r\n");
      out.write("\t\t\t\t\t<li><input type=\"button\" class=\"btn btn-light\" id=\"memberInfoUpdate\" value=\"내정보수정\" /></li> \r\n");
      out.write("\t\t\t\t\t<li><input type=\"button\" class=\"btn btn-light\" id=\"menu2\" value=\"메뉴2\" /></li>\r\n");
      out.write("\t\t\t\t\t<li><input type=\"button\" class=\"btn btn-light\" id=\"menu3\" value=\"메뉴3\" /></li>\r\n");
      out.write("\t\t\t\t\t<li></li>\r\n");
      out.write("\t\t\t\t\t<li></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"item-body\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
